In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
%timeit [j**2 for j in range(1,9)]

293 ns ± 2.73 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [21]:
import numpy as np
%timeit np.arange(1,9)**4

795 ns ± 9.22 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Linespace

WAP to find the linspace.

In [3]:
a=np.linspace(1,5,num=10)
print(a)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]


# Arange function

In [5]:
x=np.arange(-1,10,2)
print(x)

[-1  1  3  5  7  9]


# NUMPY.ONES

In [6]:
x=np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# NUMPY.ZEROS

In [7]:
x=np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Using RANDOM Function

In [8]:
x=np.random.rand(5,2)
print(x)

[[0.00123837 0.03538461]
 [0.24714979 0.78421435]
 [0.24435569 0.28837296]
 [0.61091699 0.1048139 ]
 [0.04139931 0.06954637]]


# Array Operations

WAP to find the dimension of array.

In [9]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
print(x.shape)

(3, 3)


# Addition of array

WAP to find the addition of array (column wise).

In [5]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
print(x)
np.sum(x,axis=0) #column wise addition

[[1 2 3]
 [2 3 8]
 [6 7 8]]


array([ 9, 12, 19])

WAP to find the addition of the array(row wise).

In [6]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.sum(x,axis=1) #row wise addition

array([ 6, 15, 24])

WAP to find the addition of two array.

In [12]:
#addition of two array
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
y=np.array([[1,2,4],[2,3,9],[6,7,8]])
print("first array")
print(x)
print("second array")
print(y)
print("Addition of two array")
np.add(x,y)

first array
[[1 2 3]
 [2 3 8]
 [6 7 8]]
second array
[[1 2 4]
 [2 3 9]
 [6 7 8]]
Addition of two array


array([[ 2,  4,  7],
       [ 4,  6, 17],
       [12, 14, 16]])

WAP to find the subtraction of two array.

In [13]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
y=np.array([[1,2,4],[2,3,9],[6,7,8]])
print("first array")
print(x)
print("second array")
print(y)
print("resulting array")
np.subtract(x,y)

first array
[[1 2 3]
 [2 3 8]
 [6 7 8]]
second array
[[1 2 4]
 [2 3 9]
 [6 7 8]]
resulting array


array([[ 0,  0, -1],
       [ 0,  0, -1],
       [ 0,  0,  0]])

WAP to find the multiplication of two array.

In [14]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
y=np.array([[1,2,4],[2,3,9],[6,7,8]])
print("first array")
print(x)
print("second array")
print(y)
print("Multiplication of two array")
np.multiply(x,y)

first array
[[1 2 3]
 [2 3 8]
 [6 7 8]]
second array
[[1 2 4]
 [2 3 9]
 [6 7 8]]
Multiplication of two array


array([[ 1,  4, 12],
       [ 4,  9, 72],
       [36, 49, 64]])

WAP to find the division of two array.

In [15]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
y=np.array([[1,2,4],[2,3,9],[6,7,8]])
print("first array")
print(x)
print("second array")
print(y)
print("division of two array")
np.divide(x,y)

first array
[[1 2 3]
 [2 3 8]
 [6 7 8]]
second array
[[1 2 4]
 [2 3 9]
 [6 7 8]]
division of two array


array([[1.        , 1.        , 0.75      ],
       [1.        , 1.        , 0.88888889],
       [1.        , 1.        , 1.        ]])

WAP to find the transpose of two array.

In [16]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
np.transpose(x)

array([[1, 2, 6],
       [2, 3, 7],
       [3, 8, 8]])

WAP to insert a row in a array.

In [9]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
y=np.append(x,[[3,5,7]],axis=0)
print(y)

[[1 2 3]
 [2 3 8]
 [6 7 8]
 [3 5 7]]


WAP to insert an element in an array at the particular index.

In [10]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
y=np.insert(x,1,[6,7,8],axis=0)
print(y)

[[1 2 3]
 [6 7 8]
 [2 3 8]
 [6 7 8]]


WAP to delete an element in an array at the particular index.

In [19]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
print(x)
print("deleted array at particular index")
y=np.delete(x,2,axis=0)
print(y)

[[1 2 3]
 [2 3 8]
 [6 7 8]]
deleted array at particular index
[[1 2 3]
 [2 3 8]]


WAP to perform the multiplication of different dimension in an array

In [20]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
y=np.array([[1,2,3,7],[2,3,8,5],[6,7,8,9]])
print(x)
print(y)
np.multiply(x,y)

[[1 2 3]
 [2 3 8]
 [6 7 8]]
[[1 2 3 7]
 [2 3 8 5]
 [6 7 8 9]]


ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

WAP to perform the remainder between two array.

In [15]:
x=np.array([[1,2,3],[2,3,8],[6,7,8]])
print('First array is:\n',x)
print('Second array is:\n',y)
t=np.array([[1,2,8],[8,3,8],[9,7,8]])
z=np.remainder(x,t)
print(z)

First array is:
 [[1 2 3]
 [2 3 8]
 [6 7 8]]
Second array is:
 [[1 2 8]
 [8 3 8]
 [9 7 8]]
[[0 0 3]
 [2 0 0]
 [6 0 0]]
